### PR TITLE
Slide by attribute

### PR DESCRIPTION
**Pull request by novito**
# Problem

Sometimes you want to slide, but you don't know the index, but rather you know the value of an attribute of one of the slides

# Solution

Allow sliding by an attribute and its value

### CODE REVIEW

**Comment by novito** [comment]
@lyfeyaj let me know what do you think of this. I found it useful in my project, where I didn't know the index that I wanted to slide, but I knew I wanted to slide to a specific slide that had a specific attribute-value.

**Comment by pyrsmk** [comment]
@novito Isn't it out of the scope of this library? Moreover, it seems that if you can find a slide by its attribute value, then you can find its index too, isn't it?

**Comment by novito** [comment]
@pyrsmk I forgot the context of this, but I recall it being really useful when you just have attributes and not indices. Feel free to close it though :)

**Comment by pyrsmk** [comment]
@novito No problem ;) But YOU feel free to close it, because I'm not the owner of this project at all :p

**Pull request closed without merging**
