### PR TITLE
Fixes issue when bundling with rollup.js: "this" is undefined in fact…

### PR DESCRIPTION
**Pull request by groman00**
Fixes issue when bundling with rollup.js: "this" is undefined in factory function.

### CODE REVIEW

**Comment by lyfeyaj** [comment]
Please use version `swipejs@2.1.1`

**Comment by kintesh** [comment]
This breaks bundling with webpack.

**Comment by lyfeyaj** [comment]
Yeah, it really seems break webpack's bundling, will fix it soon

**Comment by lyfeyaj** [comment]
@kintesh Fixed in `swipejs@2.1.2`

**Pull request merged**
